services:
  back-end:  # Service name (for your backend)
    build:
      context: ./back-end # Build context is the current directory (task4)
      dockerfile: Dockerfile #Dockerfile for back-end
    image: softy-pinko-back-end:task4
    ports:
      - "5252:5252"  # Map port 5252 inside the container to 5252 on the host

  front-end:  # Service name (for your frontend)
    build:
      context: ./front-end
      dockerfile: Dockerfile #Dockerfile for front-end
    image: softy-pinko-front-end:task4
    ports:
      - "9000:9000"  # Map port 9000 inside the container to 9000 on the host
    depends_on:  # Front-end depends on the back-end
      - back-end