# Use the latest Ubuntu as the base image
FROM ubuntu:latest

# Update APT repository and upgrade packages
RUN apt-get update && apt-get upgrade -y

# Set up a command to echo "Hello, World!" when the container runs
CMD echo "Hello, World!"
