version: '3'
services:
  front-end:
    image: front-end-image
    ports:
      - "80:80"
    depends_on:
      - back-end-1
      - back-end-2
    networks:
      - proxy-network
  back-end-1:
    image: back-end-image
    networks:
      - proxy-network
  back-end-2:
    image: back-end-image
    networks:
      - proxy-network
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - front-end
      - back-end-1
      - back-end-2
    networks:
      - proxy-network
networks:
  proxy-network:
    driver: bridge
