version: '3'
services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: my-proxy
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
    networks:
      - mynetwork

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task4
    expose:
      - "9000"  # Exponer el puerto 9000 dentro de la red de Docker
    networks:
      - mynetwork
  
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task4
    expose:
      - "5252"  # Exponer el puerto 5252 dentro de la red de Docker
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
